name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@HEAD

      - name: Use local my-action
        uses: ./.github/actions
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: './coverage1.xml,./coverage2.xml'
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
