name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name : Set up JDK 11
        uses : actions/setup-java@v1
        with :
          java-version : 11
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          version: "v0.1.15"
          files: './coverage1.xml,./coverage2.xml'
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          
