name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: './coverage1.xml,./coverage2.xml'
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)